"""create energy consumption table

Revision ID: cc40da2627b9
Revises: 
Create Date: 2026-08-28 09:58:41.729631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc40da2627b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_consumption_id'), 'energy_consumption', ['id'], unique=False)
    op.create_index(op.f('ix_energy_consumption_timestamp'), 'energy_consumption', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_consumption_timestamp'), table_name='energy_consumption')
    op.drop_index(op.f('ix_energy_consumption_id'), table_name='energy_consumption')
    op.drop_table('energy_consumption')
    # ### end Alembic commands ###
