import { useEffect, useMemo, useState } from "react";

import {
  Activity,
  AlertCircle,
  BarChart3,
  BatteryCharging,
  BrainCircuit,
  CheckCircle2,
  Cloud,
  Gauge,
  Download,
  Leaf,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Sun,
  TrendingDown,
  Wind,
  Zap,
} from "lucide-react";

import api from "../services/api";
import "../styles/carbon-intelligence.css";

/* =========================================================
   HELPERS
========================================================= */

const round = (value, digits = 2) =>
  Number(Number(value || 0).toFixed(digits));

const formatNumber = (value, digits = 2) =>
  Number(value || 0).toLocaleString(undefined, {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });

const formatDate = (date) => {
  if (!date) return "--";

  return new Date(`${date}T00:00:00`).toLocaleDateString(
    undefined,
    {
      month: "short",
      day: "numeric",
    }
  );
};

const getScoreClass = (score) => {
  if (score >= 80) return "excellent";
  if (score >= 60) return "good";
  if (score >= 40) return "moderate";
  return "needs-improvement";
};

const getScoreLabel = (score) => {
  if (score >= 80) return "Excellent";
  if (score >= 60) return "Good";
  if (score >= 40) return "Moderate";
  return "Needs Improvement";
};

const formatScenarioName = (scenario) => {
  if (!scenario) return "Carbon Optimization";

  return scenario
    .replaceAll("_", " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
};

/* =========================================================
   COMPONENT
========================================================= */

export default function CarbonIntelligence() {
  const [summary, setSummary] = useState(null);
  const [trend, setTrend] = useState([]);
  const [sustainability, setSustainability] = useState(null);
  const [report, setReport] = useState(null);

  const [aiInsights, setAiInsights] = useState(null);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiError, setAiError] = useState("");

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");

  const [pdfLoading, setPdfLoading] = useState(false);

  /* =========================================================
     LOAD CARBON DATA
  ========================================================= */

  const loadCarbonData = async (isRefresh = false) => {
    try {
      if (isRefresh) {
        setRefreshing(true);
      } else {
        setLoading(true);
      }

      setError("");

      const [
        summaryResponse,
        trendResponse,
        sustainabilityResponse,
        reportResponse,
      ] = await Promise.all([
        api.get(
          "/api/v1/carbon-intelligence/summary"
        ),

        api.get(
          "/api/v1/carbon-intelligence/trend"
        ),

        api.get(
          "/api/v1/carbon-intelligence/sustainability"
        ),

        api.get(
          "/api/v1/carbon-intelligence/report"
        ),
      ]);

      setSummary(summaryResponse.data || null);

      setTrend(
        Array.isArray(trendResponse.data)
          ? trendResponse.data
          : []
      );

      setSustainability(
        sustainabilityResponse.data || null
      );

      setReport(
        reportResponse.data || null
      );
    } catch (err) {
      console.error(
        "Carbon Intelligence error:",
        err
      );

      setError(
        err?.response?.data?.detail ||
          "Unable to load Carbon Intelligence data."
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  /* =========================================================
     AI CARBON INSIGHTS
  ========================================================= */

  const loadAIInsights = async () => {
    try {
      setAiLoading(true);
      setAiError("");

      const response = await api.get(
        "/api/v1/carbon-intelligence/ai/insights"
      );

      setAiInsights(response.data || null);
    } catch (err) {
      console.error(
        "AI Carbon Insights Error:",
        err
      );

      setAiError(
        err?.response?.data?.detail ||
          "Unable to load AI carbon insights."
      );
    } finally {
      setAiLoading(false);
    }
  };

  /* =========================================================
     BACKEND PDF EXPORT
     
     IMPORTANT:
     PDF is generated by FastAPI backend.
     Frontend receives application/pdf as a Blob
     and downloads it.
  ========================================================= */

  const exportCarbonReport = async () => {
    try {
      setPdfLoading(true);
      setError("");

      const response = await api.get(
        "/api/v1/carbon-intelligence/report/pdf",
        {
          responseType: "blob",
        }
      );

      if (
        !response?.data ||
        response.data.size === 0
      ) {
        throw new Error(
          "The server returned an empty PDF."
        );
      }

      const contentType =
        response.headers?.["content-type"] || "";

      if (
        !contentType.includes("application/pdf")
      ) {
        throw new Error(
          "The server did not return a PDF file."
        );
      }

      /* =====================================================
         CREATE TEMPORARY DOWNLOAD URL
      ===================================================== */

      const blob = new Blob(
        [response.data],
        {
          type: "application/pdf",
        }
      );

      const downloadUrl =
        window.URL.createObjectURL(blob);

      /* =====================================================
         READ SERVER-SUPPLIED FILENAME
      ===================================================== */

      let filename =
        "GridPulse_Carbon_Intelligence_Report.pdf";

      const contentDisposition =
        response.headers?.[
          "content-disposition"
        ];

      if (contentDisposition) {
        const filenameMatch =
          contentDisposition.match(
            /filename="?([^"]+)"?/i
          );

        if (filenameMatch?.[1]) {
          filename =
            filenameMatch[1];
        }
      }

      /* =====================================================
         DOWNLOAD PDF
      ===================================================== */

      const link =
        document.createElement("a");

      link.href = downloadUrl;
      link.download = filename;

      document.body.appendChild(link);
      link.click();
      link.remove();

      /* =====================================================
         CLEANUP
      ===================================================== */

      window.URL.revokeObjectURL(
        downloadUrl
      );
    } catch (err) {
      console.error(
        "Carbon PDF export error:",
        err
      );

      /*
        Axios may receive an error response as Blob.
        Try to extract the backend error message.
      */

      let message =
        "Unable to generate Carbon Intelligence PDF.";

      if (
        err?.response?.data instanceof Blob
      ) {
        try {
          const errorText =
            await err.response.data.text();

          const parsed =
            JSON.parse(errorText);

          if (parsed?.detail) {
            message = parsed.detail;
          }
        } catch {
          // Keep default PDF error message.
        }
      } else if (
        err?.response?.data?.detail
      ) {
        message =
          err.response.data.detail;
      } else if (err?.message) {
        message = err.message;
      }

      setError(message);
    } finally {
      setPdfLoading(false);
    }
  };

  /* =========================================================
     INITIAL LOAD
  ========================================================= */

  useEffect(() => {
    loadCarbonData();
    loadAIInsights();
  }, []);

  /* =========================================================
     TREND STATISTICS
  ========================================================= */

  const trendStats = useMemo(() => {
    if (!trend.length) {
      return {
        highestReduction: 0,
        highestAvoided: 0,
        latestReduction: 0,
      };
    }

    const highestReduction = Math.max(
      ...trend.map(
        (item) =>
          Number(
            item.carbon_reduction_percent
          ) || 0
      )
    );

    const highestAvoided = Math.max(
      ...trend.map(
        (item) =>
          Number(
            item.co2_avoided_kg
          ) || 0
      )
    );

    const latest =
      trend[trend.length - 1];

    return {
      highestReduction:
        round(highestReduction),

      highestAvoided:
        round(highestAvoided),

      latestReduction:
        round(
          latest?.carbon_reduction_percent
        ),
    };
  }, [trend]);

  /* =========================================================
     CARBON BARS
  ========================================================= */

  const carbonBars = useMemo(() => {
    if (!trend.length) return [];

    const maxEmission = Math.max(
      ...trend.map(
        (item) =>
          Number(
            item.baseline_co2_kg
          ) || 0
      ),
      1
    );

    return trend.map((item) => {
      const baseline =
        Number(
          item.baseline_co2_kg
        ) || 0;

      const actual =
        Number(
          item.estimated_co2_kg
        ) || 0;

      return {
        ...item,

        baselineWidth:
          Math.min(
            (baseline /
              maxEmission) *
              100,
            100
          ),

        actualWidth:
          Math.min(
            (actual /
              maxEmission) *
              100,
            100
          ),
      };
    });
  }, [trend]);

  /* =========================================================
     RENEWABLE MIX
  ========================================================= */

  const renewableMix = useMemo(() => {
    if (!summary) return [];

    const solar =
      Number(
        summary.total_solar_generation_kwh
      ) || 0;

    const wind =
      Number(
        summary.total_wind_generation_kwh
      ) || 0;

    const total = solar + wind || 1;

    return [
      {
        label: "Solar",
        value: solar,
        percentage:
          (solar / total) * 100,
        icon: Sun,
      },

      {
        label: "Wind",
        value: wind,
        percentage:
          (wind / total) * 100,
        icon: Wind,
      },
    ];
  }, [summary]);

  /* =========================================================
     SCORE
  ========================================================= */

  const score =
    Number(
      sustainability?.sustainability_score ??
        summary?.sustainability_score ??
        0
    ) || 0;

  const scoreClass =
    getScoreClass(score);

  /* =========================================================
     LOADING
  ========================================================= */

  if (loading) {
    return (
      <div className="carbon-page carbon-loading-page">
        <div className="carbon-loading-card">
          <div className="carbon-loading-icon">
            <Leaf size={30} />
          </div>

          <h2>
            Loading Carbon Intelligence
          </h2>

          <p>
            Synchronizing grid sustainability
            telemetry...
          </p>

          <div className="carbon-loading-spinner">
            <RefreshCw size={20} />
          </div>
        </div>
      </div>
    );
  }

  /* =========================================================
     ERROR
  ========================================================= */

  if (error) {
    return (
      <div className="carbon-page">
        <div className="carbon-error-card">
          <div className="carbon-error-icon">
            <AlertCircle size={30} />
          </div>

          <div>
            <h2>
              Carbon Intelligence unavailable
            </h2>

            <p>{error}</p>

            <button
              className="carbon-primary-btn"
              onClick={() =>
                loadCarbonData()
              }
            >
              <RefreshCw size={17} />

              Retry Connection
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="carbon-page">

      {/* =====================================================
          HEADER
      ===================================================== */}

      <header className="carbon-header">
        <div className="carbon-header-content">

          <div className="carbon-title-area">

            <div className="carbon-title-icon">
              <Leaf size={27} />
            </div>

            <div>
              <div className="carbon-eyebrow">
                GRIDPULSE • SUSTAINABILITY INTELLIGENCE
              </div>

              <h1>
                Carbon Intelligence
              </h1>

              <p>
                Monitor carbon impact, renewable
                utilization and grid sustainability
                performance.
              </p>
            </div>

          </div>

          <div className="carbon-header-actions">

            <div className="carbon-live-pill">
              <span className="carbon-live-dot" />
              LIVE TELEMETRY
            </div>

            <button
              className="carbon-refresh-btn"
              onClick={() =>
                loadCarbonData(true)
              }
              disabled={refreshing}
            >
              <RefreshCw
                size={17}
                className={
                  refreshing
                    ? "carbon-spin"
                    : ""
                }
              />

              {refreshing
                ? "Syncing..."
                : "Refresh"}
            </button>

          </div>

        </div>
      </header>

      {/* =====================================================
          KPI GRID
      ===================================================== */}

      <section className="carbon-kpi-grid">

        <div className="carbon-kpi-card">

          <div className="carbon-kpi-top">

            <div className="carbon-kpi-icon emission">
              <Cloud size={21} />
            </div>

            <span className="carbon-kpi-label">
              ESTIMATED GRID CO₂
            </span>

          </div>

          <div className="carbon-kpi-value">
            {formatNumber(
              summary?.estimated_grid_co2_kg
            )}

            <small>
              kg
            </small>
          </div>

          <div className="carbon-kpi-sub">
            Current estimated emissions
          </div>

        </div>

        <div className="carbon-kpi-card highlight">

          <div className="carbon-kpi-top">

            <div className="carbon-kpi-icon avoided">
              <TrendingDown size={21} />
            </div>

            <span className="carbon-kpi-label">
              CO₂ AVOIDED
            </span>

          </div>

          <div className="carbon-kpi-value">
            {formatNumber(
              summary?.estimated_co2_avoided_kg
            )}

            <small>
              kg
            </small>
          </div>

          <div className="carbon-kpi-positive">

            <TrendingDown size={14} />

            {formatNumber(
              summary?.carbon_reduction_percent
            )}

            % reduction

          </div>

        </div>

        <div className="carbon-kpi-card">

          <div className="carbon-kpi-top">

            <div className="carbon-kpi-icon renewable">
              <Zap size={21} />
            </div>

            <span className="carbon-kpi-label">
              RENEWABLE CONTRIBUTION
            </span>

          </div>

          <div className="carbon-kpi-value">

            {formatNumber(
              summary?.renewable_contribution_percent
            )}

            <small>
              %
            </small>

          </div>

          <div className="carbon-kpi-sub">

            {formatNumber(
              summary?.total_renewable_generation_kwh
            )}{" "}
            kWh renewable generation

          </div>

        </div>

        <div className="carbon-kpi-card">

          <div className="carbon-kpi-top">

            <div className="carbon-kpi-icon sustainability">
              <ShieldCheck size={21} />
            </div>

            <span className="carbon-kpi-label">
              SUSTAINABILITY SCORE
            </span>

          </div>

          <div className="carbon-kpi-value">

            {formatNumber(score)}

            <small>
              /100
            </small>

          </div>

          <div
            className={`carbon-status-text ${scoreClass}`}
          >
            {getScoreLabel(score)}
          </div>

        </div>

      </section>

      {/* =====================================================
          AI CARBON ADVISOR
      ===================================================== */}

      <section className="carbon-ai-section">

        <div className="carbon-ai-header">

          <div className="carbon-ai-title">

            <div className="carbon-ai-icon">
              <BrainCircuit size={22} />
            </div>

            <div>

              <span className="carbon-section-eyebrow">
                AI DECISION ENGINE
              </span>

              <h2>
                Carbon Intelligence Advisor
              </h2>

              <p>
                Explainable scenario optimization for
                lower emissions and higher renewable
                utilization.
              </p>

            </div>

          </div>

          <button
            type="button"
            className="carbon-ai-refresh"
            onClick={loadAIInsights}
            disabled={aiLoading}
          >

            <RefreshCw
              size={16}
              className={
                aiLoading
                  ? "spin"
                  : ""
              }
            />

            {aiLoading
              ? "Analyzing..."
              : "Run AI Analysis"}

          </button>

        </div>

        {aiError && (
          <div className="carbon-ai-error">

            <AlertCircle size={18} />

            <span>
              {aiError}
            </span>

          </div>
        )}

        {aiLoading && !aiInsights ? (
          <div className="carbon-ai-loading">

            <BrainCircuit size={28} />

            <span>
              AI engine is evaluating renewable and
              battery scenarios...
            </span>

          </div>
        ) : aiInsights ? (
          <>

            <div className="ai-recommendation-card">

              <div className="ai-recommendation-main">

                <div className="ai-badge">
                  <Sparkles size={15} />
                  AI RECOMMENDATION
                </div>

                <h3>
                  {formatScenarioName(
                    aiInsights.recommended_scenario
                  )}
                </h3>

                <p>
                  The optimization engine selected this
                  scenario because it provides the strongest
                  projected sustainability improvement among
                  the evaluated strategies.
                </p>

                <div className="ai-reason-list">

                  {Array.isArray(
                    aiInsights.reasons
                  ) &&
                    aiInsights.reasons.map(
                      (reason, index) => (
                        <div
                          className="ai-reason"
                          key={index}
                        >
                          <CheckCircle2 size={17} />

                          <span>
                            {reason}
                          </span>
                        </div>
                      )
                    )}

                </div>

              </div>

              <div className="ai-recommendation-metrics">

                <div className="ai-impact-metric">

                  <span>
                    CO₂ SAVING
                  </span>

                  <strong>
                    {Number(
                      aiInsights.expected_co2_saving_kg ||
                        0
                    ).toFixed(2)}
                  </strong>

                  <small>
                    kg projected
                  </small>

                </div>

                <div className="ai-impact-metric">

                  <span>
                    SUSTAINABILITY
                  </span>

                  <strong>
                    +
                    {Number(
                      aiInsights.sustainability_score_change ||
                        0
                    ).toFixed(2)}
                  </strong>

                  <small>
                    score improvement
                  </small>

                </div>

                <div className="ai-confidence">

                  <span>
                    MODEL CONFIDENCE
                  </span>

                  <strong>
                    {aiInsights.model_confidence ||
                      "--"}
                  </strong>

                </div>

              </div>

            </div>

            <div className="ai-scenario-grid">

              {Array.isArray(
                aiInsights.all_scenarios
              ) &&
                aiInsights.all_scenarios.map(
                  (item) => {

                    const isRecommended =
                      item.scenario ===
                      aiInsights.recommended_scenario;

                    let ScenarioIcon =
                      Sparkles;

                    if (
                      item.scenario ===
                      "solar_boost"
                    ) {
                      ScenarioIcon = Sun;
                    }

                    if (
                      item.scenario ===
                      "wind_boost"
                    ) {
                      ScenarioIcon = Wind;
                    }

                    if (
                      item.scenario ===
                      "renewable_boost"
                    ) {
                      ScenarioIcon = Leaf;
                    }

                    if (
                      item.scenario ===
                      "battery_optimization"
                    ) {
                      ScenarioIcon =
                        BatteryCharging;
                    }

                    if (
                      item.scenario ===
                      "peak_demand"
                    ) {
                      ScenarioIcon = Gauge;
                    }

                    if (
                      item.scenario ===
                      "renewable_drop"
                    ) {
                      ScenarioIcon = Cloud;
                    }

                    return (
                      <div
                        className={`ai-scenario-card ${
                          isRecommended
                            ? "recommended"
                            : ""
                        }`}
                        key={item.scenario}
                      >

                        <div className="ai-scenario-top">

                          <div className="ai-scenario-icon">
                            <ScenarioIcon size={20} />
                          </div>

                          {isRecommended && (
                            <span className="ai-best-tag">
                              BEST
                            </span>
                          )}

                        </div>

                        <h4>
                          {formatScenarioName(
                            item.scenario
                          )}
                        </h4>

                        <div className="ai-scenario-value">

                          <strong>
                            {Number(
                              item.expected_co2_saving_kg ||
                                0
                            ).toFixed(2)}
                          </strong>

                          <span>
                            kg CO₂ saving
                          </span>

                        </div>

                        <div className="ai-scenario-footer">

                          <span>
                            Sustainability
                          </span>

                          <strong>
                            +
                            {Number(
                              item.sustainability_score_change ||
                                0
                            ).toFixed(2)}
                          </strong>

                        </div>

                      </div>
                    );
                  }
                )}

            </div>

            <div className="ai-engine-footer">

              <div>
                <Activity size={15} />

                <span>
                  {aiInsights.engine ||
                    "Explainable Carbon Optimization Engine"}
                </span>
              </div>

              <div>
                <Zap size={15} />

                <span>
                  {aiInsights.optimization_type ||
                    "Scenario-based optimization"}
                </span>
              </div>

              <div>
                <Cloud size={15} />

                <span>
                  {aiInsights.scenarios_evaluated
                    ?.length || 0}{" "}
                  scenarios evaluated
                </span>
              </div>

            </div>

          </>
        ) : null}

      </section>

      {/* =====================================================
          PERFORMANCE OVERVIEW
      ===================================================== */}

      <section className="carbon-main-grid">

        <div className="carbon-panel carbon-performance-panel">

          <div className="carbon-panel-header">

            <div>

              <span className="carbon-panel-eyebrow">
                CARBON PERFORMANCE
              </span>

              <h2>
                Emission Impact
              </h2>

            </div>

            <div className="carbon-panel-icon">
              <BarChart3 size={20} />
            </div>

          </div>

          <div className="carbon-emission-comparison">

            <div className="carbon-emission-row">

              <div className="carbon-emission-info">

                <span>
                  Baseline emissions
                </span>

                <strong>
                  {formatNumber(
                    summary?.baseline_co2_kg
                  )}{" "}
                  kg CO₂
                </strong>

              </div>

              <div className="carbon-emission-track">

                <div
                  className="carbon-emission-fill baseline"
                  style={{
                    width: "100%",
                  }}
                />

              </div>

            </div>

            <div className="carbon-emission-row">

              <div className="carbon-emission-info">

                <span>
                  Estimated grid emissions
                </span>

                <strong>
                  {formatNumber(
                    summary?.estimated_grid_co2_kg
                  )}{" "}
                  kg CO₂
                </strong>

              </div>

              <div className="carbon-emission-track">

                <div
                  className="carbon-emission-fill actual"
                  style={{
                    width: `${
                      summary?.baseline_co2_kg
                        ? Math.min(
                            (Number(
                              summary.estimated_grid_co2_kg
                            ) /
                              Number(
                                summary.baseline_co2_kg
                              )) *
                              100,
                            100
                          )
                        : 0
                    }%`,
                  }}
                />

              </div>

            </div>

          </div>

          <div className="carbon-impact-callout">

            <div className="carbon-impact-icon">
              <Leaf size={20} />
            </div>

            <div>

              <span>
                Estimated environmental impact
              </span>

              <strong>
                {formatNumber(
                  summary?.estimated_co2_avoided_kg
                )}{" "}
                kg CO₂ avoided
              </strong>

              <p>
                Renewable generation is offsetting
                conventional grid energy in the
                current telemetry period.
              </p>

            </div>

          </div>

        </div>

        {/* =====================================================
            RENEWABLE MIX
        ===================================================== */}

        <div className="carbon-panel">

          <div className="carbon-panel-header">

            <div>

              <span className="carbon-panel-eyebrow">
                RENEWABLE IMPACT
              </span>

              <h2>
                Clean Energy Mix
              </h2>

            </div>

            <div className="carbon-panel-icon">
              <Sparkles size={20} />
            </div>

          </div>

          <div className="carbon-renewable-total">

            <div>

              <span>
                Total renewable generation
              </span>

              <strong>
                {formatNumber(
                  summary?.total_renewable_generation_kwh
                )}{" "}
                <small>
                  kWh
                </small>
              </strong>

            </div>

            <div className="carbon-renewable-percent">
              {formatNumber(
                summary?.renewable_contribution_percent
              )}
              %
            </div>

          </div>

          <div className="carbon-mix-list">

            {renewableMix.map((item) => {

              const Icon = item.icon;

              return (
                <div
                  className="carbon-mix-item"
                  key={item.label}
                >

                  <div className="carbon-mix-item-head">

                    <div className="carbon-mix-label">

                      <Icon size={17} />

                      <span>
                        {item.label}
                      </span>

                    </div>

                    <strong>
                      {formatNumber(
                        item.value
                      )}{" "}
                      kWh
                    </strong>

                  </div>

                  <div className="carbon-mix-track">

                    <div
                      className="carbon-mix-fill"
                      style={{
                        width: `${Math.min(
                          item.percentage,
                          100
                        )}%`,
                      }}
                    />

                  </div>

                  <span className="carbon-mix-percent">

                    {formatNumber(
                      item.percentage
                    )}
                    % of renewable generation

                  </span>

                </div>
              );
            })}

          </div>

        </div>

      </section>

      {/* =====================================================
          GRID METRICS
      ===================================================== */}

      <section className="carbon-metric-strip">

        <div className="carbon-mini-card">

          <div className="carbon-mini-icon">
            <Gauge size={19} />
          </div>

          <div>

            <span>
              Energy Demand
            </span>

            <strong>
              {formatNumber(
                summary?.total_energy_demand_kwh
              )}{" "}
              kWh
            </strong>

          </div>

        </div>

        <div className="carbon-mini-card">

          <div className="carbon-mini-icon">
            <Sun size={19} />
          </div>

          <div>

            <span>
              Solar Generation
            </span>

            <strong>
              {formatNumber(
                summary?.total_solar_generation_kwh
              )}{" "}
              kWh
            </strong>

          </div>

        </div>

        <div className="carbon-mini-card">

          <div className="carbon-mini-icon">
            <Wind size={19} />
          </div>

          <div>

            <span>
              Wind Generation
            </span>

            <strong>
              {formatNumber(
                summary?.total_wind_generation_kwh
              )}{" "}
              kWh
            </strong>

          </div>

        </div>

        <div className="carbon-mini-card">

          <div className="carbon-mini-icon">
            <Activity size={19} />
          </div>

          <div>

            <span>
              Carbon Intensity
            </span>

            <strong>
              {formatNumber(
                summary?.carbon_intensity_kg_per_kwh
              )}{" "}
              kg/kWh
            </strong>

          </div>

        </div>

      </section>

      {/* =====================================================
          TREND
      ===================================================== */}

      <section className="carbon-panel carbon-trend-panel">

        <div className="carbon-panel-header">

          <div>

            <span className="carbon-panel-eyebrow">
              HISTORICAL INTELLIGENCE
            </span>

            <h2>
              Carbon Reduction Trend
            </h2>

            <p>
              Daily comparison between baseline and
              estimated grid emissions.
            </p>

          </div>

          <div className="carbon-trend-summary">

            <div>

              <span>
                Peak reduction
              </span>

              <strong>
                {formatNumber(
                  trendStats.highestReduction
                )}
                %
              </strong>

            </div>

            <div>

              <span>
                Peak CO₂ avoided
              </span>

              <strong>
                {formatNumber(
                  trendStats.highestAvoided
                )}{" "}
                kg
              </strong>

            </div>

          </div>

        </div>

        <div className="carbon-chart">

          {carbonBars.length === 0 ? (
            <div className="carbon-empty">
              No trend data available.
            </div>
          ) : (
            <>

              <div className="carbon-chart-legend">

                <span>
                  <i className="legend-baseline" />
                  Baseline CO₂
                </span>

                <span>
                  <i className="legend-actual" />
                  Estimated CO₂
                </span>

              </div>

              <div className="carbon-bars">

                {carbonBars.map((item) => (

                  <div
                    className="carbon-bar-column"
                    key={item.date}
                  >

                    <div className="carbon-bar-values">

                      <span>
                        {formatNumber(
                          item.carbon_reduction_percent
                        )}
                        %
                      </span>

                    </div>

                    <div className="carbon-bar-area">

                      <div
                        className="carbon-bar baseline-bar"
                        style={{
                          height: `${Math.max(
                            item.baselineWidth,
                            3
                          )}%`,
                        }}
                        title={`Baseline: ${item.baseline_co2_kg} kg`}
                      />

                      <div
                        className="carbon-bar actual-bar"
                        style={{
                          height: `${Math.max(
                            item.actualWidth,
                            3
                          )}%`,
                        }}
                        title={`Estimated: ${item.estimated_co2_kg} kg`}
                      />

                    </div>

                    <span className="carbon-bar-date">

                      {formatDate(
                        item.date
                      )}

                    </span>

                  </div>

                ))}

              </div>

            </>
          )}

        </div>

      </section>

      {/* =====================================================
          SUSTAINABILITY + RECOMMENDATIONS
      ===================================================== */}

      <section className="carbon-main-grid">

        <div className="carbon-panel sustainability-panel">

          <div className="carbon-panel-header">

            <div>

              <span className="carbon-panel-eyebrow">
                SUSTAINABILITY INTELLIGENCE
              </span>

              <h2>
                Grid Sustainability Score
              </h2>

            </div>

            <div className="carbon-panel-icon">
              <ShieldCheck size={20} />
            </div>

          </div>

          <div className="carbon-score-layout">

            <div
              className={`carbon-score-ring ${scoreClass}`}
              style={{
                "--score": `${
                  Math.min(
                    score,
                    100
                  ) * 3.6
                }deg`,
              }}
            >

              <div className="carbon-score-inner">

                <strong>
                  {formatNumber(score, 0)}
                </strong>

                <span>
                  / 100
                </span>

              </div>

            </div>

            <div className="carbon-score-details">

              <span
                className={`carbon-score-status ${scoreClass}`}
              >
                {sustainability?.sustainability_status ||
                  getScoreLabel(score)}
              </span>

              <div className="carbon-score-item">

                <span>
                  Renewable contribution
                </span>

                <strong>
                  {formatNumber(
                    sustainability?.renewable_contribution_percent
                  )}
                  %
                </strong>

              </div>

              <div className="carbon-score-item">

                <span>
                  Carbon reduction
                </span>

                <strong>
                  {formatNumber(
                    sustainability?.carbon_reduction_percent
                  )}
                  %
                </strong>

              </div>

              <div className="carbon-score-item">

                <span>
                  Energy efficiency
                </span>

                <strong>
                  {formatNumber(
                    sustainability?.energy_efficiency_score
                  )}
                  /100
                </strong>

              </div>

            </div>

          </div>

          <div className="carbon-score-note">

            <Sparkles size={16} />

            <span>
              {sustainability?.analysis_method ||
                "GridPulse sustainability analysis"}
            </span>

          </div>

        </div>

        <div className="carbon-panel recommendation-panel">

          <div className="carbon-panel-header">

            <div>

              <span className="carbon-panel-eyebrow">
                GRIDPULSE INTELLIGENCE
              </span>

              <h2>
                AI Sustainability Actions
              </h2>

            </div>

            <div className="carbon-panel-icon">
              <Sparkles size={20} />
            </div>

          </div>

          <div className="carbon-recommendations">

            {(
              sustainability?.recommendations ||
              report?.recommendations ||
              []
            ).map(
              (recommendation, index) => (

                <div
                  className="carbon-recommendation"
                  key={`${index}-${recommendation}`}
                >

                  <div className="carbon-recommendation-number">
                    {String(index + 1).padStart(
                      2,
                      "0"
                    )}
                  </div>

                  <div>

                    <strong>
                      Sustainability Action
                    </strong>

                    <p>
                      {recommendation}
                    </p>

                  </div>

                </div>

              )
            )}

          </div>

        </div>

      </section>

      {/* =====================================================
          EXECUTIVE REPORT
      ===================================================== */}

      <section className="carbon-panel carbon-report-panel">

        <div className="carbon-panel-header">

          <div>

            <span className="carbon-panel-eyebrow">
              EXECUTIVE REPORTING
            </span>

            <h2>
              {report?.report_title ||
                "Carbon & Sustainability Report"}
            </h2>

            <p>
              Consolidated sustainability intelligence
              generated from GridPulse telemetry.
            </p>

          </div>

          <button
            type="button"
            className="carbon-export-btn"
            onClick={exportCarbonReport}
            disabled={pdfLoading}
          >

            <Download size={16} />

            {pdfLoading
              ? "Generating PDF..."
              : "Export PDF"}

          </button>

        </div>

        <div className="carbon-report-grid">

          <div className="carbon-report-block">

            <span>
              Reporting Records
            </span>

            <strong>
              {report?.reporting_records
                ?.energy_records || 0}{" "}
              Energy
            </strong>

            <small>
              {report?.reporting_records
                ?.renewable_records || 0}{" "}
              Renewable
            </small>

          </div>

          <div className="carbon-report-block">

            <span>
              CO₂ Performance
            </span>

            <strong>
              {formatNumber(
                report?.carbon_performance
                  ?.estimated_co2_avoided_kg
              )}{" "}
              kg avoided
            </strong>

            <small>
              {formatNumber(
                report?.carbon_performance
                  ?.carbon_reduction_percent
              )}
              % reduction
            </small>

          </div>

          <div className="carbon-report-block">

            <span>
              Renewable Performance
            </span>

            <strong>
              {formatNumber(
                report?.renewable_performance
                  ?.total_renewable_generation_kwh
              )}{" "}
              kWh
            </strong>

            <small>
              {formatNumber(
                report?.renewable_performance
                  ?.renewable_contribution_percent
              )}
              % contribution
            </small>

          </div>

          <div className="carbon-report-block">

            <span>
              Battery Reserve
            </span>

            <strong>
              {formatNumber(
                report?.renewable_performance
                  ?.average_battery_storage_kwh
              )}{" "}
              kWh
            </strong>

            <small>
              Average storage telemetry
            </small>

          </div>

        </div>

        <div className="carbon-report-footer">

          <CheckCircle2 size={16} />

          <span>
            {report?.report_method ||
              "Calculated from GridPulse energy and renewable telemetry."}
          </span>

        </div>

      </section>

      {/* =====================================================
          FOOTER STATUS
      ===================================================== */}

      <footer className="carbon-footer">

        <div>

          <span className="carbon-footer-dot" />

          Carbon Intelligence Engine Online

        </div>

        <span>

          {summary?.energy_records || 0}{" "}
          energy records

          {" • "}

          {summary?.renewable_records || 0}{" "}
          renewable records

        </span>

        <span>

          Last sync:

          {" "}

          {summary?.generated_at
            ? new Date(
                summary.generated_at
              ).toLocaleTimeString()
            : "--"}

        </span>

      </footer>

    </div>
  );
}
